#!/usr/bin/env sh
set -eu

echo "🚀 Running linter!"
npx lint-staged
echo ""

echo "🚀 Checking branchname!"
local_branch_name=$(git rev-parse --abbrev-ref HEAD)
valid_branch_regex='^(feature|hotfix|bugfix)/[0-9]+-[a-zA-Z0-9\-]+$'

if ! echo "$local_branch_name" | grep -Eq "$valid_branch_regex"; then
    printf "\033[31m⚠️ Branchname does not adhere to naming convention %s! \033[0m\n" "$valid_branch_regex"
else
    echo "✅  Branchname!"
fi
echo ""

echo "🚀 Checking translation keys!"
if ! npm run i18n:find >/dev/null 2>&1; then
    printf "\033[31m⚠️ Translation keys missing or unused! \033[0m\n"
else
    echo "✅  Translation keys!"
fi
echo ""
